[dependencies]
arrow = {version = "54", features = ["pyarrow"]}
chrono = "0.4"
pyo3 = {version = "0.23", features = ["extension-module"]}
rdkafka = "0.37"

[lib]
crate-type = ["cdylib"]
name = "kafkars"

[package]
edition = "2021"
license = "Apache-2.0"
name = "kafkars"
version = "0.1.0"
