[package]
name = "kafkars"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
name = "kafkars"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
rdkafka = "0.37"
